import { DefaultMantineColor } from '@mantine/core';
import { Icon } from '@phosphor-icons/react';
import { BowlFood, BuildingApartment, CalendarCheck, CallBell, Scooter, TShirt } from '@phosphor-icons/react/dist/ssr';
import { ActionFilters } from './types';
import { Author } from 'next/dist/lib/metadata/types/metadata-types';

export const metaAuthors: Author[] = [
  { name: 'Padeo', url: 'https://www.padeo.fr' },
  { name: 'OryxChange', url: process?.env?.NEXT_PUBLIC_AUTH_APPINFO_WEBSITEDOMAIN || '' }
];
export const SEARCH_RESULT_LIFETIME = 2_592_000; // 30 days
export const PAGINATION_LIMIT = 48;
export type Theme = 'foods' | 'goods' | 'transports' | 'events' | 'services' | 'accommodations';
export const landingPagesUrl = new Map<Theme, string>([
  ['accommodations', '/fr/logement'],
  ['foods', '/fr/alimentation'],
  ['goods', '/fr/mes-achats'],
  ['transports', '/fr/transport-responsable'],
]);
export const TAGSPLITTER = '|||';

export const themesIcons: { [key: string]: Icon } = {
  foods: BowlFood,
  accommodations: BuildingApartment,
  goods: TShirt,
  services: CallBell,
  transports: Scooter,
  events: CalendarCheck
};

export const themesColors: { [key: string]: DefaultMantineColor } = {
  transports: 'blue.7',
  foods: 'blue.7',
  goods: 'blue.7',
  events: 'blue.7',
  services: 'blue.7',
  accommodations: 'blue.7'
};

export const themes: Theme[] = ['foods', 'goods', 'transports', 'events', 'services', 'accommodations'];

export const imagesMapping: { [key: string]: string } = {
  // accommodations
  'acheter une pompe à chaleur': 'energySystem',
  "comparer d'énergies vertes": 'compareEnergy',
  'construire décarboné': 'buildLowCarbon',
  'économiser la chaleur': 'heatSaving',
  "économiser l'électricité": 'electricitySaving',
  "économiser l'énergie": 'electricitySaving',
  'installer des panneaux voltaïques / chauffe-eau solaire': 'energySystem',
  "produire de l'énergie renouvelable": 'renewableEnergy',
  'rénover son logement': 'renovation',
  'se chauffer au bois ou granulés': 'energySystem',
  'système énergétique': 'energySystem',

  // foods
  déchets: 'reduceWaste',
  'devenir végétalien': 'proteinDiversity',
  flexitarien: 'proteinDiversity',
  'origine et qualité des produits': 'foods',
  'produits végétaux & animaux': 'proteinDiversity',
  'réduire la consommation d’origine animale': 'proteinDiversity',
  'régime alimentaire': 'proteinDiversity',
  'remplacer la viande rouge': 'proteinDiversity',
  'remplacer les protéines animales': 'proteinDiversity',
  'remplacer les produits laitiers': 'replaceDairy',
  'réduire ses déchets': 'reduceWaste',
  'privilégier le circuit court': 'shortCircuit',
  'consommer de saison': 'seasonal',
  'réduire ses déchets organiques': 'reduceWaste',
  'diversifier sa consommation de protéines (insectes, simili, algues)': 'proteinDiversity',
  'consommer bio': 'foods',

  // goods
  'acheter eco-construits/biosourcé': 'ecoBuilt',
  "acheter/vendre d'occasion ou reconditionné": 'secondHand',
  "acheter/vendre d'occasion ou reconditionné - les généralistes": 'secondHand',
  "acheter/vendre d'occasion ou reconditionné - les spécialistes": 'secondHand',
  animaux: 'ecoBuilt',
  'art de la table': 'ecoBuilt',
  autre: 'ecoDesign',
  cosmétique: 'diy',
  'eco-concevoir': 'ecoDesign',
  electronique: 'diy',
  "faire de l'économie circulaire": 'ecoDesign',
  'faire soi-même (DIY)': 'diy',
  'famille, enfant, bébé': 'ecoBuilt',
  'hygiène, santé, beauté': 'diy',
  informatique: 'diy',
  internet: 'diy',
  'loisirs, sport et culture': 'share',
  'loisirs, sport et culture, jeux jouets': 'share',
  louer: 'rent',
  'maison & jardin': 'ecoBuilt',
  'mieux acheter': 'ecoDesign',
  mode: 'secondHand',
  'mode, bijoux': 'secondHand',
  'mode, bijoux, lunettes': 'secondHand',
  mutualiser: 'share',
  'produits pour le corps et la peau': 'diy',
  relocaliser: 'relocate',
  réparer: 'repair',
  réutiliser: 'reuse',
  véhicule: 'repair',
  électroménager: 'repair',

  // services
  'aides financières': 'financialAid',
  comparateur: 'comparator',
  'comparateur de banques': 'banking',
  loisirs: 'sports',
  restaurants: 'restaurant',
  sorties: 'outings',
  vacances: 'holidays',

  // events
  atelier: 'events',
  'ateliers de sensibilisation': 'events',
  bijoux: 'restaurant',
  conférence: 'banking',
  créateurs: 'events',
  décoration: 'events',
  débat: 'financialAid',
  forum: 'financialAid',
  'forum, journées pour les particuliers': 'financialAid',
  'fresques du climat': 'repaircomputer',
  'journées pour les particuliers': 'financialAid',
  marché: 'outings',
  recyclage: 'repaircomputer',
  'salon journées professionnelles': 'banking',
  upcycling: 'repaircomputer',
  vêtements: 'restaurant',

  // transports
  'acheter une voiture bas carbone': 'cars',
  'auto partage': 'carsharing',
  'augmenter le taux de remplissage': 'carsharing',
  'bateau (cargo, voile, ferry)': 'boat',
  'co-voiturer': 'carpooling',
  'co-working': 'telework',
  covoiturer: 'carpooling',
  electrique: 'cars',
  entretenir: 'cars',
  'écosystème pour mobilité douce': 'bikes',
  marcher: 'walk',
  'mobilité douce': 'bikes',
  monoroue: 'monowheel',
  'petits moyens de transport': 'scooter',
  'se déplacer à vélo': 'bikes',
  'se déplacer en avion': 'transports',
  'se déplacer en bateau de croisière': 'boat',
  'se déplacer en voiture diesel': 'cars',
  'se déplacer en voiture électrique': 'cars',
  'se déplacer en voiture essence': 'cars',
  'se déplacer en voiture gpl': 'cars',
  'se déplacer en voiture hydrogène': 'cars',
  'se déplacer en voiture hybride': 'car-hybrid',
  'se déplacer en moto': 'moto',
  télétravailler: 'telework',
  train: 'transports',
  triporteurs: 'bikes',
  trottinettes: 'scooter',
  'utiliser le bateau - cargo - voile ferry': 'boat',
  'utiliser les transports publics': 'transports',
  vélo: 'bikes',
  voiture: 'cars',
  'voiture sans permis': 'cars',
  'voyager - se déplacer': 'travel',
  voyages: 'transports'
  
};

export const getActionFilters = ({ themes = [] }: { themes?: Theme[] }): ActionFilters => {
  let actions: ActionFilters = { economic: 'boolean', ess: 'boolean' };

  return actions;
};

export const REGIONS = [
  '01',
  '02',
  '2A',
  '2B',
  '03',
  '04',
  '05',
  '06',
  '07',
  '08',
  '09',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30',
  '31',
  '32',
  '33',
  '34',
  '35',
  '36',
  '37',
  '38',
  '39',
  '40',
  '41',
  '42',
  '43',
  '44',
  '45',
  '46',
  '47',
  '48',
  '49',
  '50',
  '51',
  '52',
  '53',
  '54',
  '55',
  '56',
  '57',
  '58',
  '59',
  '60',
  '61',
  '62',
  '63',
  '64',
  '65',
  '66',
  '67',
  '68',
  '69',
  '70',
  '71',
  '72',
  '73',
  '74',
  '75',
  '76',
  '77',
  '78',
  '79',
  '80',
  '81',
  '82',
  '83',
  '84',
  '85',
  '86',
  '87',
  '88',
  '89',
  '90',
  '91',
  '92',
  '93',
  '94',
  '95',
  '971',
  '972',
  '973',
  '974',
  '976'
];

export const LOCATIONS = ['online', 'store', 'store-and-online'];
